apiVersion: v1
kind: ConfigMap
metadata:
  name: app-environment
data:
  spring_profiles_active: "mysql"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/petclinic"
  SPRING_DATASOURCE_USERNAME: "petclinic"
  SPRING_DATASOURCE_PASSWORD: "petclinic"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_SQL_INIT_MODE: "always"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  strategy: {}
  template:
    metadata:

      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: yogendra/spring-petclinic
        name: spring-petclinic
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: app-environment
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: spring-petclinic
  type: ClusterIP
